import random
while True:
    a=random.randint(1,3)
    b=input("请出拳(每次电脑出的都不一样)：")
    b=str(b)
    if(a==1):
        if(b=="石头"):
            print("平局!")
        elif(b=="剪刀"):
            print("电脑赢了!")
        elif(b=="布"):
            print("你赢了!")
            break
        else:
            print("输入错误")
            break
    elif(a==2):
        if(b=="石头"):
            print("你赢了!")
            break
        elif(b=="剪刀"):
            print("平局!")
        elif(b=="布"):
            print("电脑赢了!")
        else:
            print("输入错误")
            break
    elif(a==3):
        if(b=="石头"):
            print("电脑赢了!")
        elif(b=="剪刀"):
            print("你赢了!")
            break
        elif(b=="布"):
            print("平局!")
        else:
            print("输入错误")
            break
